name: Autotests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  autotests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install npm deps
        run: npm ci

      - name: Set Gayscale filter for fonts
        run: |
          mkdir -p ~/.config/fontconfig/conf.d
          cat > ~/.config/fontconfig/conf.d/10-antialias-grayscale.conf <<EOF
          <?xml version='1.0'?>
          <!DOCTYPE fontconfig SYSTEM 'urn:fontconfig:fonts.dtd'>
          <fontconfig>
            <match target="font">
              <edit name="antialias" mode="assign">
                <bool>true</bool>
              </edit>
              <edit name="hinting" mode="assign">
                <bool>true</bool>
              </edit>
              <edit name="rgba" mode="assign">
                <const>none</const>
              </edit>
              <edit name="lcdfilter" mode="assign">
                <const>lcddefault</const>
              </edit>
            </match>
          </fontconfig>
          EOF

      - name: Install Noto Sans Mono Font
        run: |
          wget -O NotoSansMono-Regular.ttf https://fonts.gstatic.com/s/notosansmono/v32/BngrUXNETWXI6LwhGYvaxZikqZqK6fBq6kPvUce2oAZcdthSBUsYck4-_FNJ49rXVEQQL8Y.ttf
          mv NotoSansMono-Regular.ttf /usr/share/fonts/
          fc-cache -fv

      - name: Run linter SCSS
        run: npm run lint:scss

      - name: Run linter TS
        run: npm run lint:ts

      - name: Run typecheck
        run: npm run typecheck

      - name: Run unit tests
        run: npm run test:unit

      - name: Run UI tests
        id: testplane
        uses: gemini-testing/gh-actions-testplane@v1
        with:
          config-path: "config/testplane/testplane.storybook.config.ts"
          storybook: "true"

      - name: Archive UI tests report
        if: failure() && steps.testplane.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: ui-tests-report
          path: testplane-reports
